---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Compile'
        uses: xu-cheng/latex-action@v4
        with:
          pre_compile: ./create-aux-dirs.sh
          root_file: dissertation.tex
          args:
      - name: 'Upload'
        uses: actions/upload-artifact@v4
        with:
          name: dissertation
          path: dissertation.pdf
